import Navbar from "./components/navbar";
import Footer from "./components/footer";
import FooterTwo from "./components/FooterTwo";
import "./globals.css";
export const metadata = {
  title: "Supportta Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />  
        {children}  
        <FooterTwo />
        <Footer />
      </body>
    </html>
  );
}
